Repository Architech-DORA/sample1, pull requests merged in 2023-05, with the labels that each got.

#3 Delete sample3.sh
  sample3.sh
Labels: deployment

#5 Create sample3.sh
  sample3.sh
Labels: enhancement, deployment

#6 deploy the sample 4
  sample4.sh
Labels: bug, incident

#12 closes DORA-4
  issue.sh
Labels: bug

#13 closes DORA-2 Dev-0101
  dev.sh
Labels: deployment

#16 closes DORA-13-feature12
  feature12.sh
Labels: deployment

#17 Update feature12.sh
  feature12.sh
Labels: deployment
